<a href="https://colab.research.google.com/github/Dev-Maidul/Pandas/blob/main/pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Sakib"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,70000]
}
df=pd.DataFrame(data)

In [3]:
df

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [4]:
df.loc[df['City'].str.contains("New")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [5]:
df.loc[df['City'].str.contains("New",case=False)]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [6]:
# starts with Los
df.loc[df['City'].str.contains(r"^Los")]

  Name         City Department  Salary
1  Bob  Los Angeles         IT   60000

In [7]:
#end with rk
df.loc[df['City'].str.contains(r"rk$")]

      Name      City Department  Salary
0    Alice  New York         HR   50000
2  Charlie    Newark    Finance   55000

In [8]:
# name starts with a vowel
df.loc[df['Name'].str.contains(r"^[AEILU]")]

    Name       City Department  Salary
0  Alice   New York         HR   50000
4    Eve  New Delhi         HR   52000

In [9]:
# string contains New or Los
df.loc[df['City'].str.contains(r"New | Los")]

    Name         City Department  Salary
0  Alice     New York         HR   50000
4    Eve    New Delhi         HR   52000
6  Grace  New Orleans    Finance   62000
8  Sakib    H Los Ang         HR   70000

# Adding New Column

In [12]:
df = pd.read_csv('student_data.csv')
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [ ]:
# adding a column with constant value
df['Country']="Bangladesh"
df

In [ ]:
df['Total Marks']=df['Algorithm Marks']+df['Python Marks']
df

In [ ]:
import numpy as np
df["A+ in DS"]=np.where(df['Data Structure Marks']>90,"A+","A")
df

In [ ]:
# check how many student pass in DS where marks >70
df["Passed in Ds"]=df['Data Structure Marks']>70
df

In [ ]:
# Add a column in first Name
df["First Name"]=df['FullName'].str.split(" ").str[0]
df

In [ ]:
# Save all changes on external file also
df.to_csv('new_data.csv')

# Unique and nunique

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 85, 95, 90]
}

df = pd.DataFrame(data)
df

In [ ]:
# Unique works only series
df['Name'].unique()

In [ ]:
df1=pd.read_csv('student_data.csv')
df1

In [ ]:
len(df1['Data Structure Marks'].unique())
df1['Data Structure Marks'].unique()

In [ ]:
df1['Data Structure Marks'].nunique()

# Check null

In [ ]:
df1.isnull()

In [ ]:
df1['Data Structure Marks'].isnull()

In [ ]:
df1['Data Structure Marks'].notnull()

In [ ]:
df1["Data Structure Marks"].hasnans

In [ ]:
df1[['FullName','StudentID']]

# Handling Duplicate Values

In [ ]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 70, 95, 90]
}

df = pd.DataFrame(data)
df

In [ ]:
df.duplicated().sum()

In [ ]:
# delelting duplicates values
df.drop_duplicates()

In [ ]:
# permanent delete duplicate value
df.drop_duplicates(inplace=True)
df

In [ ]:
#  name er basis e duplicate deletion
df.drop_duplicates(subset="Name")

In [ ]:
# city
df.drop_duplicates(subset="City")

In [ ]:
df.drop_duplicates(subset=['Name'],keep='last')

In [ ]:
df.drop_duplicates(subset=['Name'],keep='first')

# Handling Null values

In [ ]:
df=pd.read_csv('student_data.csv')
df

In [ ]:
df.dropna()

In [ ]:
df.dropna(how='all',inplace=True)

In [ ]:
df

In [ ]:
df.dropna(subset=['Python Marks'])

In [ ]:
df.dropna(subset=['Python Marks','Algorithm Marks'])

In [ ]:
df

In [ ]:
df.fillna(0)

In [ ]:
df = pd.read_csv('student_data.csv')

df

In [ ]:
df['FullName'].fillna('unknown')

In [ ]:
df['Python Marks'].fillna(df['Python Marks'].mean(),inplace=True)
df

# Statistical Functions

In [ ]:
df

In [ ]:
df.dropna()

In [ ]:
# sum
df['Data Structure Marks'].sum()

In [ ]:
# Max and Min
print(df['Data Structure Marks'].max())
print(df['Data Structure Marks'].min())

In [ ]:
#mean -> average
df['Data Structure Marks'].mean()

In [ ]:
#median
df['Data Structure Marks'].median()

In [ ]:
# mode -> highest frequency er number
df['Data Structure Marks'].mode()

In [ ]:
# standard deviation -> std
df['Data Structure Marks'].std()

In [ ]:
# correlation matrix

df[['Data Structure Marks','Python Marks']].corr()

In [ ]:
# sum in different columns row wise
df[['Data Structure Marks','Python Marks']].sum(axis=1)

In [ ]:
df["Total Marks"]=df.iloc[::,2:5].sum(axis=1)
df

In [ ]:
df.describe()

In [ ]:
df

# apply function on df

In [ ]:
#min max scaling
df.dropna()
mn=df['Total Marks'].min()
mx=df['Algorithm Marks'].max()
df["Scaled Mark"]=df['Total Marks'].apply(lambda x: (x-mn)/(mx-mn))

In [ ]:
df

In [ ]:
# custom built function
def grading_system(marks):
  if marks>=260:
    return 'A+'
  elif marks>=250:
    return 'A'
  else:
    return 'A-'

df['Grade']=df['Total Marks'].apply(grading_system)

In [ ]:
df

In [ ]:
def marking_system(df):
  a=df['Data Structure Marks']*2
  b=df['Algorithm Marks']*3
  c=df['Python Marks']*4

  return a+b+c

df["Exceptional Marks"]=df.apply(marking_system,axis=1)

In [ ]:
df

# datetime and time delta

In [ ]:
df = pd.read_csv('student_completed_data.csv')
df

In [ ]:
df['EnrollmentDate']

In [ ]:
df['EnrollmentDate']=pd.to_datetime(df['EnrollmentDate'])
df['EnrollmentDate']

In [ ]:
df["Enrolment Year"]=df['EnrollmentDate'].dt.year

In [ ]:
df

In [ ]:
df["Enroment Month"]=df['EnrollmentDate'].dt.month
df

In [ ]:
df['FinishedDate']=pd.to_datetime(df['FinishedDate'])

In [ ]:
df["Total time to finish"]=df['EnrollmentDate']-df['FinishedDate']

In [ ]:
df

# Groupby

In [13]:
import numpy as np

df.loc[df['FullName'] == 'Afsana Mimi', 'Total Marks'] = np.nan
df.loc[df['FullName'] == 'Sadia Chowdhury', 'Total Marks'] = np.nan
df.loc[df['FullName'] == 'Alif Rahman', 'Total Marks'] = np.nan

In [14]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,NaN
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,NaN
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,NaN
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,NaN
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,NaN
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,NaN
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,NaN
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,NaN
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,NaN
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,NaN
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,NaN
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,NaN

In [16]:
instructor_group=df.groupby('Instructor')
instructor_group

In [18]:
for instructor,df_ins in instructor_group:
  print(instructor)
  display(df_ins)

Mr. David

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,NaN
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,NaN
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN

Mr. Karim

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,NaN
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,NaN

Ms. Salma

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,NaN
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,NaN
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,NaN

In [19]:
instructor_group.min()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,Total Marks
Instructor,,,,,,,,,
Mr. David,PH1009,Faria Rahman,72.0,72.0,76.0,Completed,2024-05-16,Chattogram,NaN
Mr. Karim,PH1001,Afsana Mimi,80.0,80.0,84.0,Completed,2024-01-15,Chattogram,NaN
Ms. Salma,PH1002,Babul Ahmed,75.0,75.0,78.0,Completed,2024-01-20,Chattogram,NaN

In [21]:
instructor_group.describe()

           Data Structure Marks                                          \
                          count       mean       std   min    25%   50%
Instructor
Mr. David                   2.0  73.500000  2.121320  72.0  72.75  73.5
Mr. Karim                   5.0  85.800000  3.768289  80.0  85.00  86.0
Ms. Salma                   9.0  85.333333  6.324555  75.0  81.00  86.0

                        Algorithm Marks             ... Python Marks        \
              75%   max           count       mean  ...          75%   max
Instructor                                          ...
Mr. David   74.25  75.0             2.0  73.500000  ...        78.25  79.0
Mr. Karim   88.00  90.0             5.0  85.800000  ...        92.50  95.0
Ms. Salma   89.00  94.0             9.0  85.333333  ...        87.50  89.0

           Total Marks
                 count mean std min 25% 50% 75% max
Instructor
Mr. David          0.0  NaN NaN NaN NaN NaN NaN NaN
Mr. Karim          0.0  NaN NaN NaN NaN NaN NaN NaN
Ms. Salma          0.0  NaN NaN NaN NaN NaN NaN NaN

[3 rows x 32 columns]