<a href="https://colab.research.google.com/github/Dev-Maidul/Pandas/blob/main/pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Sakib"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,70000]
}
df=pd.DataFrame(data)

In [2]:
df

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [3]:
df.loc[df['City'].str.contains("New")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [4]:
df.loc[df['City'].str.contains("New",case=False)]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [10]:
# starts with Los
df.loc[df['City'].str.contains(r"^Los")]

  Name         City Department  Salary
1  Bob  Los Angeles         IT   60000

In [11]:
#end with rk
df.loc[df['City'].str.contains(r"rk$")]

      Name      City Department  Salary
0    Alice  New York         HR   50000
2  Charlie    Newark    Finance   55000

In [12]:
# name starts with a vowel
df.loc[df['Name'].str.contains(r"^[AEILU]")]

    Name       City Department  Salary
0  Alice   New York         HR   50000
4    Eve  New Delhi         HR   52000

In [13]:
# string contains New or Los
df.loc[df['City'].str.contains(r"New | Los")]

    Name         City Department  Salary
0  Alice     New York         HR   50000
4    Eve    New Delhi         HR   52000
6  Grace  New Orleans    Finance   62000
8  Sakib    H Los Ang         HR   70000